/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppRunsRouteImport } from './routes/_app/runs'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppOpsIndexRouteImport } from './routes/_app/ops/index'
import { Route as AppOpsActivityRouteImport } from './routes/_app/ops/activity'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectRouteImport } from './routes/_app/projects/$project'
import { Route as AppOpsWebsitesSourceIdRouteImport } from './routes/_app/ops/websites/$sourceId'
import { Route as AppProjectsProjectIndexRouteImport } from './routes/_app/projects/$project/index'
import { Route as AppProjectsProjectFieldsRouteImport } from './routes/_app/projects/$project/fields'
import { Route as AppProjectsProjectOutputRouteImport } from './routes/_app/projects/$project/output'
import { Route as AppProjectsProjectSettingsRouteImport } from './routes/_app/projects/$project/settings'
import { Route as AppProjectsProjectSitesSiteRouteImport } from './routes/_app/projects/$project/sites/$site'
import { Route as AppProjectsProjectSitesSiteIndexRouteImport } from './routes/_app/projects/$project/sites/$site/index'
import { Route as AppProjectsProjectSitesSiteExtractRouteImport } from './routes/_app/projects/$project/sites/$site/extract'
import { Route as AppProjectsProjectSitesSiteSettingsRouteImport } from './routes/_app/projects/$project/sites/$site/settings'
import { Route as AppProjectsProjectSitesSiteRunsIndexRouteImport } from './routes/_app/projects/$project/sites/$site/runs/index'
import { Route as AppProjectsProjectSitesSiteRunsRunRouteImport } from './routes/_app/projects/$project/sites/$site/runs/$run'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppOpsIndexRoute = AppOpsIndexRouteImport.update({
  id: '/ops/',
  path: '/ops/',
  getParentRoute: () => AppRoute,
} as any)
const AppOpsActivityRoute = AppOpsActivityRouteImport.update({
  id: '/ops/activity',
  path: '/ops/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectRoute = AppProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => AppRoute,
} as any)
const AppOpsWebsitesSourceIdRoute = AppOpsWebsitesSourceIdRouteImport.update({
  id: '/ops/websites/$sourceId',
  path: '/ops/websites/$sourceId',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIndexRoute = AppProjectsProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsProjectRoute,
} as any)
const AppProjectsProjectFieldsRoute =
  AppProjectsProjectFieldsRouteImport.update({
    id: '/fields',
    path: '/fields',
    getParentRoute: () => AppProjectsProjectRoute,
  } as any)
const AppProjectsProjectOutputRoute =
  AppProjectsProjectOutputRouteImport.update({
    id: '/output',
    path: '/output',
    getParentRoute: () => AppProjectsProjectRoute,
  } as any)
const AppProjectsProjectSettingsRoute =
  AppProjectsProjectSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectRoute,
  } as any)
const AppProjectsProjectSitesSiteRoute =
  AppProjectsProjectSitesSiteRouteImport.update({
    id: '/sites/$site',
    path: '/sites/$site',
    getParentRoute: () => AppProjectsProjectRoute,
  } as any)
const AppProjectsProjectSitesSiteIndexRoute =
  AppProjectsProjectSitesSiteIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AppProjectsProjectSitesSiteRoute,
  } as any)
const AppProjectsProjectSitesSiteExtractRoute =
  AppProjectsProjectSitesSiteExtractRouteImport.update({
    id: '/extract',
    path: '/extract',
    getParentRoute: () => AppProjectsProjectSitesSiteRoute,
  } as any)
const AppProjectsProjectSitesSiteSettingsRoute =
  AppProjectsProjectSitesSiteSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AppProjectsProjectSitesSiteRoute,
  } as any)
const AppProjectsProjectSitesSiteRunsIndexRoute =
  AppProjectsProjectSitesSiteRunsIndexRouteImport.update({
    id: '/runs/',
    path: '/runs/',
    getParentRoute: () => AppProjectsProjectSitesSiteRoute,
  } as any)
const AppProjectsProjectSitesSiteRunsRunRoute =
  AppProjectsProjectSitesSiteRunsRunRouteImport.update({
    id: '/runs/$run',
    path: '/runs/$run',
    getParentRoute: () => AppProjectsProjectSitesSiteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/runs': typeof AppRunsRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/ops/activity': typeof AppOpsActivityRoute
  '/projects/$project': typeof AppProjectsProjectRouteWithChildren
  '/ops/': typeof AppOpsIndexRoute
  '/projects/': typeof AppProjectsIndexRoute
  '/ops/websites/$sourceId': typeof AppOpsWebsitesSourceIdRoute
  '/projects/$project/fields': typeof AppProjectsProjectFieldsRoute
  '/projects/$project/output': typeof AppProjectsProjectOutputRoute
  '/projects/$project/settings': typeof AppProjectsProjectSettingsRoute
  '/projects/$project/': typeof AppProjectsProjectIndexRoute
  '/projects/$project/sites/$site': typeof AppProjectsProjectSitesSiteRouteWithChildren
  '/projects/$project/sites/$site/extract': typeof AppProjectsProjectSitesSiteExtractRoute
  '/projects/$project/sites/$site/settings': typeof AppProjectsProjectSitesSiteSettingsRoute
  '/projects/$project/sites/$site/': typeof AppProjectsProjectSitesSiteIndexRoute
  '/projects/$project/sites/$site/runs/$run': typeof AppProjectsProjectSitesSiteRunsRunRoute
  '/projects/$project/sites/$site/runs/': typeof AppProjectsProjectSitesSiteRunsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/runs': typeof AppRunsRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/ops/activity': typeof AppOpsActivityRoute
  '/ops': typeof AppOpsIndexRoute
  '/projects': typeof AppProjectsIndexRoute
  '/ops/websites/$sourceId': typeof AppOpsWebsitesSourceIdRoute
  '/projects/$project/fields': typeof AppProjectsProjectFieldsRoute
  '/projects/$project/output': typeof AppProjectsProjectOutputRoute
  '/projects/$project/settings': typeof AppProjectsProjectSettingsRoute
  '/projects/$project': typeof AppProjectsProjectIndexRoute
  '/projects/$project/sites/$site/extract': typeof AppProjectsProjectSitesSiteExtractRoute
  '/projects/$project/sites/$site/settings': typeof AppProjectsProjectSitesSiteSettingsRoute
  '/projects/$project/sites/$site': typeof AppProjectsProjectSitesSiteIndexRoute
  '/projects/$project/sites/$site/runs/$run': typeof AppProjectsProjectSitesSiteRunsRunRoute
  '/projects/$project/sites/$site/runs': typeof AppProjectsProjectSitesSiteRunsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/runs': typeof AppRunsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/ops/activity': typeof AppOpsActivityRoute
  '/_app/projects/$project': typeof AppProjectsProjectRouteWithChildren
  '/_app/ops/': typeof AppOpsIndexRoute
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/ops/websites/$sourceId': typeof AppOpsWebsitesSourceIdRoute
  '/_app/projects/$project/fields': typeof AppProjectsProjectFieldsRoute
  '/_app/projects/$project/output': typeof AppProjectsProjectOutputRoute
  '/_app/projects/$project/settings': typeof AppProjectsProjectSettingsRoute
  '/_app/projects/$project/': typeof AppProjectsProjectIndexRoute
  '/_app/projects/$project/sites/$site': typeof AppProjectsProjectSitesSiteRouteWithChildren
  '/_app/projects/$project/sites/$site/extract': typeof AppProjectsProjectSitesSiteExtractRoute
  '/_app/projects/$project/sites/$site/settings': typeof AppProjectsProjectSitesSiteSettingsRoute
  '/_app/projects/$project/sites/$site/': typeof AppProjectsProjectSitesSiteIndexRoute
  '/_app/projects/$project/sites/$site/runs/$run': typeof AppProjectsProjectSitesSiteRunsRunRoute
  '/_app/projects/$project/sites/$site/runs/': typeof AppProjectsProjectSitesSiteRunsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/runs'
    | '/settings'
    | '/usage'
    | '/ops/activity'
    | '/projects/$project'
    | '/ops/'
    | '/projects/'
    | '/ops/websites/$sourceId'
    | '/projects/$project/fields'
    | '/projects/$project/output'
    | '/projects/$project/settings'
    | '/projects/$project/'
    | '/projects/$project/sites/$site'
    | '/projects/$project/sites/$site/extract'
    | '/projects/$project/sites/$site/settings'
    | '/projects/$project/sites/$site/'
    | '/projects/$project/sites/$site/runs/$run'
    | '/projects/$project/sites/$site/runs/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/runs'
    | '/settings'
    | '/usage'
    | '/ops/activity'
    | '/ops'
    | '/projects'
    | '/ops/websites/$sourceId'
    | '/projects/$project/fields'
    | '/projects/$project/output'
    | '/projects/$project/settings'
    | '/projects/$project'
    | '/projects/$project/sites/$site/extract'
    | '/projects/$project/sites/$site/settings'
    | '/projects/$project/sites/$site'
    | '/projects/$project/sites/$site/runs/$run'
    | '/projects/$project/sites/$site/runs'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/account'
    | '/_app/runs'
    | '/_app/settings'
    | '/_app/usage'
    | '/_app/ops/activity'
    | '/_app/projects/$project'
    | '/_app/ops/'
    | '/_app/projects/'
    | '/_app/ops/websites/$sourceId'
    | '/_app/projects/$project/fields'
    | '/_app/projects/$project/output'
    | '/_app/projects/$project/settings'
    | '/_app/projects/$project/'
    | '/_app/projects/$project/sites/$site'
    | '/_app/projects/$project/sites/$site/extract'
    | '/_app/projects/$project/sites/$site/settings'
    | '/_app/projects/$project/sites/$site/'
    | '/_app/projects/$project/sites/$site/runs/$run'
    | '/_app/projects/$project/sites/$site/runs/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs': {
      id: '/_app/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ops/': {
      id: '/_app/ops/'
      path: '/ops'
      fullPath: '/ops/'
      preLoaderRoute: typeof AppOpsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ops/activity': {
      id: '/_app/ops/activity'
      path: '/ops/activity'
      fullPath: '/ops/activity'
      preLoaderRoute: typeof AppOpsActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project': {
      id: '/_app/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof AppProjectsProjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ops/websites/$sourceId': {
      id: '/_app/ops/websites/$sourceId'
      path: '/ops/websites/$sourceId'
      fullPath: '/ops/websites/$sourceId'
      preLoaderRoute: typeof AppOpsWebsitesSourceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/': {
      id: '/_app/projects/$project/'
      path: '/'
      fullPath: '/projects/$project/'
      preLoaderRoute: typeof AppProjectsProjectIndexRouteImport
      parentRoute: typeof AppProjectsProjectRoute
    }
    '/_app/projects/$project/fields': {
      id: '/_app/projects/$project/fields'
      path: '/fields'
      fullPath: '/projects/$project/fields'
      preLoaderRoute: typeof AppProjectsProjectFieldsRouteImport
      parentRoute: typeof AppProjectsProjectRoute
    }
    '/_app/projects/$project/output': {
      id: '/_app/projects/$project/output'
      path: '/output'
      fullPath: '/projects/$project/output'
      preLoaderRoute: typeof AppProjectsProjectOutputRouteImport
      parentRoute: typeof AppProjectsProjectRoute
    }
    '/_app/projects/$project/settings': {
      id: '/_app/projects/$project/settings'
      path: '/settings'
      fullPath: '/projects/$project/settings'
      preLoaderRoute: typeof AppProjectsProjectSettingsRouteImport
      parentRoute: typeof AppProjectsProjectRoute
    }
    '/_app/projects/$project/sites/$site': {
      id: '/_app/projects/$project/sites/$site'
      path: '/sites/$site'
      fullPath: '/projects/$project/sites/$site'
      preLoaderRoute: typeof AppProjectsProjectSitesSiteRouteImport
      parentRoute: typeof AppProjectsProjectRoute
    }
    '/_app/projects/$project/sites/$site/': {
      id: '/_app/projects/$project/sites/$site/'
      path: '/'
      fullPath: '/projects/$project/sites/$site/'
      preLoaderRoute: typeof AppProjectsProjectSitesSiteIndexRouteImport
      parentRoute: typeof AppProjectsProjectSitesSiteRoute
    }
    '/_app/projects/$project/sites/$site/extract': {
      id: '/_app/projects/$project/sites/$site/extract'
      path: '/extract'
      fullPath: '/projects/$project/sites/$site/extract'
      preLoaderRoute: typeof AppProjectsProjectSitesSiteExtractRouteImport
      parentRoute: typeof AppProjectsProjectSitesSiteRoute
    }
    '/_app/projects/$project/sites/$site/settings': {
      id: '/_app/projects/$project/sites/$site/settings'
      path: '/settings'
      fullPath: '/projects/$project/sites/$site/settings'
      preLoaderRoute: typeof AppProjectsProjectSitesSiteSettingsRouteImport
      parentRoute: typeof AppProjectsProjectSitesSiteRoute
    }
    '/_app/projects/$project/sites/$site/runs/': {
      id: '/_app/projects/$project/sites/$site/runs/'
      path: '/runs'
      fullPath: '/projects/$project/sites/$site/runs/'
      preLoaderRoute: typeof AppProjectsProjectSitesSiteRunsIndexRouteImport
      parentRoute: typeof AppProjectsProjectSitesSiteRoute
    }
    '/_app/projects/$project/sites/$site/runs/$run': {
      id: '/_app/projects/$project/sites/$site/runs/$run'
      path: '/runs/$run'
      fullPath: '/projects/$project/sites/$site/runs/$run'
      preLoaderRoute: typeof AppProjectsProjectSitesSiteRunsRunRouteImport
      parentRoute: typeof AppProjectsProjectSitesSiteRoute
    }
  }
}

interface AppProjectsProjectSitesSiteRouteChildren {
  AppProjectsProjectSitesSiteExtractRoute: typeof AppProjectsProjectSitesSiteExtractRoute
  AppProjectsProjectSitesSiteSettingsRoute: typeof AppProjectsProjectSitesSiteSettingsRoute
  AppProjectsProjectSitesSiteIndexRoute: typeof AppProjectsProjectSitesSiteIndexRoute
  AppProjectsProjectSitesSiteRunsRunRoute: typeof AppProjectsProjectSitesSiteRunsRunRoute
  AppProjectsProjectSitesSiteRunsIndexRoute: typeof AppProjectsProjectSitesSiteRunsIndexRoute
}

const AppProjectsProjectSitesSiteRouteChildren: AppProjectsProjectSitesSiteRouteChildren =
  {
    AppProjectsProjectSitesSiteExtractRoute:
      AppProjectsProjectSitesSiteExtractRoute,
    AppProjectsProjectSitesSiteSettingsRoute:
      AppProjectsProjectSitesSiteSettingsRoute,
    AppProjectsProjectSitesSiteIndexRoute:
      AppProjectsProjectSitesSiteIndexRoute,
    AppProjectsProjectSitesSiteRunsRunRoute:
      AppProjectsProjectSitesSiteRunsRunRoute,
    AppProjectsProjectSitesSiteRunsIndexRoute:
      AppProjectsProjectSitesSiteRunsIndexRoute,
  }

const AppProjectsProjectSitesSiteRouteWithChildren =
  AppProjectsProjectSitesSiteRoute._addFileChildren(
    AppProjectsProjectSitesSiteRouteChildren,
  )

interface AppProjectsProjectRouteChildren {
  AppProjectsProjectFieldsRoute: typeof AppProjectsProjectFieldsRoute
  AppProjectsProjectOutputRoute: typeof AppProjectsProjectOutputRoute
  AppProjectsProjectSettingsRoute: typeof AppProjectsProjectSettingsRoute
  AppProjectsProjectIndexRoute: typeof AppProjectsProjectIndexRoute
  AppProjectsProjectSitesSiteRoute: typeof AppProjectsProjectSitesSiteRouteWithChildren
}

const AppProjectsProjectRouteChildren: AppProjectsProjectRouteChildren = {
  AppProjectsProjectFieldsRoute: AppProjectsProjectFieldsRoute,
  AppProjectsProjectOutputRoute: AppProjectsProjectOutputRoute,
  AppProjectsProjectSettingsRoute: AppProjectsProjectSettingsRoute,
  AppProjectsProjectIndexRoute: AppProjectsProjectIndexRoute,
  AppProjectsProjectSitesSiteRoute:
    AppProjectsProjectSitesSiteRouteWithChildren,
}

const AppProjectsProjectRouteWithChildren =
  AppProjectsProjectRoute._addFileChildren(AppProjectsProjectRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppRunsRoute: typeof AppRunsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppOpsActivityRoute: typeof AppOpsActivityRoute
  AppProjectsProjectRoute: typeof AppProjectsProjectRouteWithChildren
  AppOpsIndexRoute: typeof AppOpsIndexRoute
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
  AppOpsWebsitesSourceIdRoute: typeof AppOpsWebsitesSourceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppRunsRoute: AppRunsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppOpsActivityRoute: AppOpsActivityRoute,
  AppProjectsProjectRoute: AppProjectsProjectRouteWithChildren,
  AppOpsIndexRoute: AppOpsIndexRoute,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
  AppOpsWebsitesSourceIdRoute: AppOpsWebsitesSourceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
