/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppRunsRouteImport } from './routes/_app/runs'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppUsageRouteImport } from './routes/_app/usage'
import { Route as AppProjectsIndexRouteImport } from './routes/_app/projects/index'
import { Route as AppProjectsProjectRouteImport } from './routes/_app/projects/$project'
import { Route as AppProjectsProjectIndexRouteImport } from './routes/_app/projects/$project/index'
import { Route as AppProjectsProjectFieldsRouteImport } from './routes/_app/projects/$project/fields'
import { Route as AppProjectsProjectOutputRouteImport } from './routes/_app/projects/$project/output'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppRunsRoute = AppRunsRouteImport.update({
  id: '/runs',
  path: '/runs',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageRoute = AppUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsIndexRoute = AppProjectsIndexRouteImport.update({
  id: '/projects/',
  path: '/projects/',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectRoute = AppProjectsProjectRouteImport.update({
  id: '/projects/$project',
  path: '/projects/$project',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsProjectIndexRoute = AppProjectsProjectIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProjectsProjectRoute,
} as any)
const AppProjectsProjectFieldsRoute =
  AppProjectsProjectFieldsRouteImport.update({
    id: '/fields',
    path: '/fields',
    getParentRoute: () => AppProjectsProjectRoute,
  } as any)
const AppProjectsProjectOutputRoute =
  AppProjectsProjectOutputRouteImport.update({
    id: '/output',
    path: '/output',
    getParentRoute: () => AppProjectsProjectRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/runs': typeof AppRunsRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/projects/$project': typeof AppProjectsProjectRouteWithChildren
  '/projects/': typeof AppProjectsIndexRoute
  '/projects/$project/fields': typeof AppProjectsProjectFieldsRoute
  '/projects/$project/output': typeof AppProjectsProjectOutputRoute
  '/projects/$project/': typeof AppProjectsProjectIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/account': typeof AppAccountRoute
  '/runs': typeof AppRunsRoute
  '/settings': typeof AppSettingsRoute
  '/usage': typeof AppUsageRoute
  '/projects': typeof AppProjectsIndexRoute
  '/projects/$project/fields': typeof AppProjectsProjectFieldsRoute
  '/projects/$project/output': typeof AppProjectsProjectOutputRoute
  '/projects/$project': typeof AppProjectsProjectIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/account': typeof AppAccountRoute
  '/_app/runs': typeof AppRunsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/usage': typeof AppUsageRoute
  '/_app/projects/$project': typeof AppProjectsProjectRouteWithChildren
  '/_app/projects/': typeof AppProjectsIndexRoute
  '/_app/projects/$project/fields': typeof AppProjectsProjectFieldsRoute
  '/_app/projects/$project/output': typeof AppProjectsProjectOutputRoute
  '/_app/projects/$project/': typeof AppProjectsProjectIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/account'
    | '/runs'
    | '/settings'
    | '/usage'
    | '/projects/$project'
    | '/projects/'
    | '/projects/$project/fields'
    | '/projects/$project/output'
    | '/projects/$project/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/account'
    | '/runs'
    | '/settings'
    | '/usage'
    | '/projects'
    | '/projects/$project/fields'
    | '/projects/$project/output'
    | '/projects/$project'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/account'
    | '/_app/runs'
    | '/_app/settings'
    | '/_app/usage'
    | '/_app/projects/$project'
    | '/_app/projects/'
    | '/_app/projects/$project/fields'
    | '/_app/projects/$project/output'
    | '/_app/projects/$project/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/runs': {
      id: '/_app/runs'
      path: '/runs'
      fullPath: '/runs'
      preLoaderRoute: typeof AppRunsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage': {
      id: '/_app/usage'
      path: '/usage'
      fullPath: '/usage'
      preLoaderRoute: typeof AppUsageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/': {
      id: '/_app/projects/'
      path: '/projects'
      fullPath: '/projects/'
      preLoaderRoute: typeof AppProjectsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project': {
      id: '/_app/projects/$project'
      path: '/projects/$project'
      fullPath: '/projects/$project'
      preLoaderRoute: typeof AppProjectsProjectRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects/$project/': {
      id: '/_app/projects/$project/'
      path: '/'
      fullPath: '/projects/$project/'
      preLoaderRoute: typeof AppProjectsProjectIndexRouteImport
      parentRoute: typeof AppProjectsProjectRoute
    }
    '/_app/projects/$project/fields': {
      id: '/_app/projects/$project/fields'
      path: '/fields'
      fullPath: '/projects/$project/fields'
      preLoaderRoute: typeof AppProjectsProjectFieldsRouteImport
      parentRoute: typeof AppProjectsProjectRoute
    }
    '/_app/projects/$project/output': {
      id: '/_app/projects/$project/output'
      path: '/output'
      fullPath: '/projects/$project/output'
      preLoaderRoute: typeof AppProjectsProjectOutputRouteImport
      parentRoute: typeof AppProjectsProjectRoute
    }
  }
}

interface AppProjectsProjectRouteChildren {
  AppProjectsProjectFieldsRoute: typeof AppProjectsProjectFieldsRoute
  AppProjectsProjectOutputRoute: typeof AppProjectsProjectOutputRoute
  AppProjectsProjectIndexRoute: typeof AppProjectsProjectIndexRoute
}

const AppProjectsProjectRouteChildren: AppProjectsProjectRouteChildren = {
  AppProjectsProjectFieldsRoute: AppProjectsProjectFieldsRoute,
  AppProjectsProjectOutputRoute: AppProjectsProjectOutputRoute,
  AppProjectsProjectIndexRoute: AppProjectsProjectIndexRoute,
}

const AppProjectsProjectRouteWithChildren =
  AppProjectsProjectRoute._addFileChildren(AppProjectsProjectRouteChildren)

interface AppRouteChildren {
  AppAccountRoute: typeof AppAccountRoute
  AppRunsRoute: typeof AppRunsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppUsageRoute: typeof AppUsageRoute
  AppProjectsProjectRoute: typeof AppProjectsProjectRouteWithChildren
  AppProjectsIndexRoute: typeof AppProjectsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAccountRoute: AppAccountRoute,
  AppRunsRoute: AppRunsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppUsageRoute: AppUsageRoute,
  AppProjectsProjectRoute: AppProjectsProjectRouteWithChildren,
  AppProjectsIndexRoute: AppProjectsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
