module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: null,
    setBlockAds: false,
    setBypassCSP: false,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    rawOptions: { checkBlocked: true },
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 6000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: '#popin_tc_privacy_button_2',
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'FR',
    domain: 'laredoute',
    schemaYAML: 'multiPages',
  },
};
