extends: ./anyNameOfYourSinglePageYamlFile
singleRecord: false
regionsSelector: null
recordSelector: null
recordXPath:  null
fields:
  - name: camelCaseNameOfTheField
    xpath: //xpath
    jq: 'jq | filter'
    regExp: '(reg)*p'
    regExpReplace: 'website$1$2'
    defaultValue: 'hardcoded value if nothing matches'
    manualSelector: css#selector
    screenCapture: 'png'
    downloadContent: 'text'
    type: 'NUMBER | BOOLEAN | STRING (default if omitted)'

