module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: null,
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    acceptCookiesCSSSelector: null,
    timeout: 200000,
    wait: 10,
    waitForCookiesSelectorTimeout: 3000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 61000,
    optTags: null,
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: true,
    rawOptions: {},
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    sumbitCaptchaOrderedActions: [],
    maxCaptcha: 3,
    captchaTimeout: 100,
    timeoutOffset: 1000,
    waitUntil: 'networkidle0',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    country: 'KR',
    domain: 'naver',
    schemaYAML: 'singlePage',
  },
};
