singleRecord: false
regionsSelector: null
recordSelector: null
recordXPath: null
fields:
  - name: channelUID
    xpath: //*[@id="preLoaded"]
    jq: if .channel then .channel[].channelUid else .smartStoreV2.channel.channelUid end
  - name: details
    xpath: //*[@id="preLoaded"]
    jq: 'if .product then .product[] else "" end'
  - name: id
    xpath: //*[@id="preLoaded"]
    jq: 'if .product then .product[].id else "" end'
  - name: channel
    xpath: //*[@id="preLoaded"]
    jq: 'if .product then .product[].channel.channelUid else "" end'
  - name: category
    xpath: //*[@id="preLoaded"]
    jq: 'if .product then .product[].category.wholeCategoryId else "" end'
  - name: productNo
    xpath: //*[@id="preLoaded"]
    jq: 'if .product then .product[].productNo else "" end'
  - name: preLoaded
    xpath: //*[@id="preLoaded"]
    # regExp: '[^{}]'
  - name: benefits
    xpath: //pre//text()