module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'FR',
    loadedXpath: '//main',
    reloadXpath: null,
    waitForSelectorToLoad: null,
    noResultsXPath: '//h1[contains(text(),"404")]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    orderedSelectorsToClickOn: [
      '.pip-chunky-header__details button',
    ],
    orderedActionsToPerform: [],
    loadingTimeout: 5000,
    checkXpathBeforeExtract: null,
    URLTemplate: null,
    setZipCode: {
      checkZipCodeSelectorOrXPath: '//button[contains(@class,"pip-delivery-section")]',
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: '//input[@id="hnf-txt-postalcodepicker-postcode"]',
        afterInputSelectorOrXPathArray: ['//span[contains(@class,"hnf-btn__inner")][.//*[contains(text(), "Enregistrer")]]'],
        wait: 3000,
      },
    },
    zipcode: '75008',
    storeID: null,
    useGoto2: true,
    schemaYAML: 'multiPages',
    mergeType: 'APPEND',
    maxScrolls: 3,
    arrayOfInputFieldNamesToAdd: null,
    addAttributeToExtractedRecords: null,
    enableAutoTable: true,
    // paginate: {
    //   stopConditionSelectorOrXpath: null,
    //   nestedPagination: {
    //     nextDepthURLFieldName: null,
    //     paginate: null,
    //   },
    //   nextLink: {
    //     nextLinkSelectorOrXpath: null,
    //     mutationSelectorOrXpath: null,
    //     spinnerSelectorOrXpath: null,
    //     nextLinkTimeout: null,
    //     waitForXpath: null,
    //   },
    //   infiniteScroll: {
    //     maxScrolls: null,
    //     stopXPath: null,
    //     waitTime: null,
    //   },
    //   openSearchDefinition: {
    //     template: null,
    //     pageStartNb: null,
    //     indexOffset: null,
    //     pageOffset: null,
    //     pageIndexMultiplier: null,
    //   },
    // },
    domain: 'ikea',
  },
};
