module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [],
    setBlockAds: false,
    setBypassCSP: false,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: false,
    force200: true,
    optTags: null,
    timeout: 60000,
    waitUntil: 'load',
    acceptCookiesCSSSelector: 'button#CybotCookiebotDialogBodyLevelButtonLevelOptinAllowAll',
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'UK',
    domain: 'juul',
    schemaYAML: 'multiPages',
  },
};
