module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [],
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    rawOptions: { checkBlocked: false },
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 60000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: null,
    captchaSelectors: { CLOUDFLARE: 'iframe[title*="Cloudflare security challenge"]' },
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'SA',
    domain: 'homecenter',
    schemaYAML: 'multiPages',
  },
};
