module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    loadedXpath: '//article[contains(@class, "mainWrapper")]/article/article',
    noResultsXPath: '//section[contains(@class,"oopsFrame")]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    loadingTimeout: 5000,
    waitForSelectorToLoad: null,
    URLTemplate: null,
    resultsTarget: 1,
    orderedSelectorsToClickOn: [],
    arrayOfInputFieldNamesToAdd: [],
    zipcode: null,
    maxScrolls: 1,
    setZipCode: {
      checkZipCodeSelectorOrXPath: '',
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    orderedActionsToPerform: [],
    addAttributeToExtractedRecords: null,
    allowScreenCaptures: null,
    checkXpathBeforeExtract: null,
    reloadXpath: null,
    loadedSelector: null,
    appendCookies: 'false',
    preProcessInputs: [],
    useGoto2: true,
    enableAutoTable: true,
    mergeType: 'APPEND',
    schemaYAML: 'extractor',
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    country: 'US',
    domain: 'montepkg',
  },
};
