module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: false,
    setBlockAds: false,
    setBypassCSP: false,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 20000,
    captchaTimeout: 3000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: '#onetrust-accept-btn-handler',
    captchaSelectors: { RECAPTCHA: '#captcha iframe' },
    submitCaptchaButtonCSS: 'input#submit',
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'US',
    domain: 'redfin',
    schemaYAML: 'multiplePage',
  },
};
