module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: null,
    setBlockAds: false,
    setBypassCSP: false,
    setLoadAllResources: true,
    setLoadImages: false,
    setCssEnabled: false,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 90000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: 'button#global-cookie-submit',
    // acceptCookiesCSSSelector: null,
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'PL',
    domain: 'home-you',
    schemaYAML: 'multiPages',
  },
};
