module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      '<xhr|script|font|stylesheet>',
    ],
    setBlockAds: true,
    setBypassCSP: true,
    setLoadAllResources: null,
    setLoadImages: null,
    setCssEnabled: null,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 60000,
    waitUntil: 'networkidle0',
    rawOptions: {},
    acceptCookiesCSSSelector: '#sp-cc-accept',
    captchaSelectors: {},
    submitCaptchaButtonCSS: 'button[type="submit"]',
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    retryGotoUntilLoadedCSSorXpath: null,
    store: null,
    country: 'GB',
    gotoRetries: null,
    domain: 'amazon',
    schemaYAML: 'singlePage',
  },
};
