module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'IN',
    loadedSelector: null,
    waitForSelectorToLoad: null,
    noResultsXPath: '//section[contains(@class,"magic_main")]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    orderedSelectorsToClickOn: [],
    orderedActionsToPerform: [],
    loadingTimeout: 5000,
    checkXpathBeforeExtract: null,
    URLTemplate: null,
    setZipCode: {
      checkZipCodeSelectorOrXPath: null,
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    zipcode: null,
    storeID: null,
    gotoOptions: { checkBlocked: true },
    useGoto2: true,
    schemaYAML: 'multiPages',
    mergeType: 'APPEND',
    arrayOfInputFieldNamesToAdd: null,
    addAttributeToExtractedRecords: null,
    maxScrolls: 0,
    enableAutoTable: true,
    // paginate: {
    //   stopConditionSelectorOrXpath: null,
    //   nestedPagination: {
    //     nextDepthURLFieldName: null,
    //     paginate: null,
    //   },
    //   nextLink: {
    //     nextLinkSelectorOrXpath: null,
    //     mutationSelectorOrXpath: null,
    //     spinnerSelectorOrXpath: null,
    //     nextLinkTimeout: null,
    //     waitForXpath: null,
    //   },
    //   infiniteScroll: {
    //     maxScrolls: null,
    //     stopXPath: null,
    //     waitTime: null,
    //   },
    //   openSearchDefinition: {
    //     template: null,
    //     pageStartNb: null,
    //     indexOffset: null,
    //     pageOffset: null,
    //     pageIndexMultiplier: null,
    //   },
    // },
    domain: 'bookmyshow',
  },
};
