module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      '<xhr|script|font|stylesheet>',
    ],
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: false,
    setLoadImages: false,
    setCssEnabled: false,
    applyIgnoreVBAndCookies: null,
    // rawOptions: { override_user_agent: 'salsifyg1crawl10262021adcgg' },
    optTags: null,
    timeout: 60000,
    captchaTimeout: 3000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: 'button[aria-label="closeDialogLabel"]',
    captchaSelectors: { PERIMETERX: 'div#px-captcha' },
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'CN',
    domain: 'walmart',
    schemaYAML: 'multiPages',
  },
};
