module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: true,
    setBlockAds: true,
    setBypassCSP: false,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: false,
    optTags: '',
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: '#cookie_close',
    captchaSelectors: false,
    waitAfterNavObject: false,
    store: 'mon-liquide',
    country: 'FR',
    domain: 'mon-liquide',
  },
};
