module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      // '<xhr|script|font|stylesheet>',
    ],
    setBlockAds: true,
    setBypassCSP: false,
    setLoadAllResources: false,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 60000,
    waitUntil: 'networkidle0',
    rawOptions: {},
    acceptCookiesCSSSelector: 'button#onetrust-accept-btn-handler',
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    retryGotoUntilLoadedCSSorXpath: null,
    store: null,
    country: 'JP',
    gotoRetries: null,
    domain: 'starto',
    schemaYAML: 'multiPages',
  },
};
