export { ScraperPipeline, type PipelineOptions, type PipelineResult } from './pipeline.js';
export { validateFieldShape, type ValidateResult } from './shape-validator.js';
export { buildExtractionScript, type ExecutorResult } from './executor.js';
export { extractFromStructuredData } from './structured-extractor.js';
export { lookupDomainCache, saveDomainCache, resolveFromCache, resolveApiPathsFromCache, buildCachedXPathScript, getByDotPath, type DomainCache, type FieldPathSet, type FieldPath, type PathSource } from './domain-cache.js';
export { extractBrand, extractRootDomain, areDomainsRelated, isSubdomain, getSubdomainPrefix } from './domain-utils.js';
export { acquireDomainLock, isDomainLocked, getActiveLocks } from './domain-lock.js';
export { detectSchemaChanges, formatSchemaChanges, type SchemaChange } from './schema-evolution.js';
export { validateExtractedData, type QualityIssue, type QualityResult } from './data-quality.js';
export { calculateFieldCoverage, getMissingFields } from './field-coverage.js';
export { normalizeUserFields } from './field-normalizer.js';
export { findEntitySubtree, type EntitySubtree } from './entity-subtree.js';
export { liveCorpus, type LiveCorpusEntry } from './__fixtures__/corpus/manifest.js';
export { corroborateValue, visibleTextFromHtml, type CorroborationResult } from './corroborate-value.js';
