export { ScraperPipeline, type PipelineOptions, type PipelineResult } from './pipeline.js';
export { validateFieldShape, type ValidateResult } from './shape-validator.js';
export { buildExtractionScript, type ExecutorResult } from './executor.js';
export { extractFromStructuredData } from './structured-extractor.js';
export { lookupDomainCache, saveDomainCache, resolveFromCache, resolveApiPathsFromCache, buildCachedXPathScript, getByDotPath, type DomainCache, type FieldPathSet, type FieldPath, type PathSource } from './domain-cache.js';
export { extractBrand, extractRootDomain, areDomainsRelated, isSubdomain, getSubdomainPrefix } from './domain-utils.js';
export { acquireDomainLock, isDomainLocked, getActiveLocks } from './domain-lock.js';
export { sanitizeCatalogue, MAX_CANDIDATES_PER_CONCEPT, type Candidate, type CandidateCatalogue, type ConceptName } from './candidate-catalogue.js';
export { detectSchemaChanges, formatSchemaChanges, type SchemaChange } from './schema-evolution.js';
export { validateExtractedData, type QualityIssue, type QualityResult } from './data-quality.js';
export { calculateFieldCoverage, getMissingFields } from './field-coverage.js';
export { normalizeUserFields } from './field-normalizer.js';
export { findEntitySubtree, type EntitySubtree } from './entity-subtree.js';
export { liveCorpus, type LiveCorpusEntry } from './__fixtures__/corpus/manifest.js';
export { corroborateValue, visibleTextFromHtml, type CorroborationResult } from './corroborate-value.js';
export { runExtraction, isAiPlaceholder, type ExtractionRequest, type ExtractionOutcome, type ExtractionDeps, type ExtractionAgent, type ExtractionFieldInput } from './extraction-orchestrator.js';
export { buildResultRows, type ResultRow, type SchemaFieldLite } from './build-result-rows.js';
export { collectAiAnalysisSources, type AnalysisSource } from './collect-ai-analysis-sources.js';
export { detectPathConflicts, sourceAuthority, type PathConflict } from './domain-cache.js';
export { prunePaths } from './domain-cache.js';
export { pinFieldPath } from './domain-cache.js';
export { saveCandidateCatalogue, clearCandidateCatalogue } from './domain-cache.js';
export { markDisplayed } from './domain-cache.js';
export { saveVerifiedRowPlan, recordRowPlanMiss, type RowSelector, type RowFieldPath } from './domain-cache.js';
export { runAnalysis, type AnalysisOutcome, type AnalysisDeps, type AnalysisAgent } from './analysis-orchestrator.js';
export { cachedFieldsFromCache, type CachedFieldSummary } from './cached-fields-from-cache.js';
export { describesSamePage, extractIdentifiers, filterEntitiesForPage, type EntityMatch } from './entity-match.js';
export { filterRequestsForPage } from './entity-match.js';
export { planRun } from './crawl/plan-run.js';
export type { PlannedItem, PlanRunOutcome, PlanRunRequest, PlanInputReport } from './crawl/plan-run.js';
export { resolveBudget, itemCap, HARD_ITEM_CEILING } from './crawl/budget.js';
export { partitionSchemaByOrigin } from './crawl/partition-schema.js';
export type { OriginField, FieldOrigin } from './crawl/partition-schema.js';
export { mergeRow } from './crawl/merge-row.js';
export { DETAIL_URL_FIELD } from './crawl/enumerate-detail-urls.js';
export { buildCataloguePrompt, parseCatalogueResponse, discoverCandidateCatalogue, type CatalogueEvidence } from './catalogue-discovery.js';
