module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      '<font|stylesheet>',
    ],
    setBlockAds: true,
    setBypassCSP: true,
    setLoadAllResources: null,
    setLoadImages: null,
    setCssEnabled: null,
    acceptCookiesCSSSelector: 'button[data-testid="uc-deny-all-button"]',
    timeout: 60000,
    waitForCookiesSelectorTimeout: 3000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 31000,
    optTags: null,
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: null,
    rawOptions: {},
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    maxCaptcha: 3,
    captchaTimeout: 5000,
    timeoutOffset: 1000,
    waitUntil: 'networkidle0',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    country: 'UK',
    domain: 'henry_schein',
    schemaYAML: 'listing',
  },
};
