module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
    // '<font|stylesheet>',
    ],
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 60000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: 'button.js-accept',
    // captchaSelectors: { RECAPTCHA: 'div#rcp iframe[title="reCAPTCHA"]', CLOUDFLARE: 'iframe[title*="Cloudflare"]', HCAPTCHA: '#cpf iframe[_src*="hcaptcha"]' },
    submitCaptchaButtonCSS: 'button.emg-button',
    maxCaptcha: 1,
    gotoRetries: 1,
    retryGotoUntilLoadedCSSorXpath: true,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'HU',
    domain: 'emag',
    schemaYAML: 'multiPages',
  },
};
