module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'HU',
    loadedXpath: '//div[contains(@class,"main-container-inner")]',
    waitForSelectorToLoad: null,
    noResultsXPath: '//h1[contains(text(),"404")]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")] | //div[contains(@class,"captcha-widget")]',
    orderedSelectorsToClickOn: [],
    orderedActionsToPerform: [],
    loadingTimeout: 5000,
    URLTemplate: null,
    setZipCode: {
      checkZipCodeSelectorOrXPath: null,
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'multiPages',
    mergeType: 'APPEND',
    maxScrolls: 0,
    arrayOfInputFieldNamesToAdd: null,
    addAttributeToExtractedRecords: null,
    enableAutoTable: true,
    domain: 'emag',
  },
};
