module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: null,
    setBlockAds: false,
    setBypassCSP: null,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 10000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: 'button[id="accept-recommended-btn-handler"]',
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'DE',
    domain: 'blu',
    schemaYAML: 'multiPages',
  },
};
