module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: ['<font>'],
    setBlockAds: false,
    setBypassCSP: false,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    // try to prevent autoredirect by geolocation
    optTags: '"cookie_jar":[{"name":"ge_redirect","value":"1", "domain":".asda.com"}]',
    timeout: 10 * 60 * 1000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: 'div.deliver-to-uk > button, #onetrust-accept-btn-handler',
    captchaSelectors: { RECAPTCHA: '.g-recaptcha iframe' },
    captchaTimeout: 20000,
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'GB',
    domain: 'asdadirect',
    schemaYAML: 'multiPages',
  },
};
