// goto2 navigation override parameter definitions.
// Source: robot-library/src/library/navigation/goto2/action.js

import type { FieldDefinition } from './parameter-definitions';

export const GOTO2_DEFINITIONS: FieldDefinition[] = [
  {
    name: 'blockUnnecessaryRequests',
    type: 'array',
    description: 'Block network requests matching these regex patterns. Set empty to allow all.',
    default: ['<xhr|script|font|stylesheet>'],
    records: 'regex',
  },
  {
    name: 'setBlockAds',
    type: 'boolean',
    description: 'Block advertisements during page load.',
    default: true,
  },
  {
    name: 'setBypassCSP',
    type: 'boolean',
    description: 'Bypass Content Security Policy on the page.',
    default: true,
  },
  {
    name: 'setLoadAllResources',
    type: 'boolean',
    description: 'Load all page resources including scripts and stylesheets.',
    default: false,
  },
  {
    name: 'setLoadImages',
    type: 'boolean',
    description: 'Load images during page navigation.',
    default: false,
  },
  {
    name: 'setCssEnabled',
    type: 'boolean',
    description: 'Load CSS stylesheets during page navigation.',
    default: false,
  },
  {
    name: 'timeout',
    type: 'time',
    description: 'Overall navigation timeout in milliseconds.',
    default: 60000,
  },
  {
    name: 'waitUntil',
    type: 'enum',
    description: 'When to consider navigation successful.',
    default: 'networkidle0',
    enumOptions: ['networkidle0', 'networkidle2', 'load', 'domcontentloaded'],
  },
  {
    name: 'acceptCookiesCSSSelector',
    type: 'css',
    description: 'CSS selector for the cookie acceptance button. Auto-clicked on page load.',
    default: '',
    optional: true,
  },
  {
    name: 'waitForCookiesSelectorTimeout',
    type: 'time',
    description: 'Timeout for waiting for cookie acceptance button to appear.',
    default: 3000,
    advanced: true,
  },
  {
    name: 'captchaSelectors',
    type: 'object',
    description: 'Map of captcha types to their CSS selectors (e.g. { RECAPTCHA: "#captcha iframe" }).',
    default: {},
    advanced: true,
    records: [],
  },
  {
    name: 'submitCaptchaButtonCSS',
    type: 'css',
    description: 'CSS selector for button to click after captcha is solved.',
    default: '',
    optional: true,
    advanced: true,
  },
  {
    name: 'maxCaptcha',
    type: 'number',
    description: 'Maximum number of captcha solve attempts.',
    default: 3,
    advanced: true,
  },
  {
    name: 'captchaTimeout',
    type: 'time',
    description: 'Timeout for each captcha solve attempt.',
    default: 5000,
    advanced: true,
  },
  {
    name: 'waitAfterNavObject',
    type: 'object',
    description: 'Handle Cloudflare-like wait pages after navigation.',
    default: {},
    advanced: true,
    records: [
      {
        name: 'wrongRedirectSelector',
        type: 'css',
        description: 'Selector matching incorrect redirect pages.',
        optional: true,
      },
      {
        name: 'selector',
        type: 'css',
        description: 'Selector to wait for after navigation.',
        optional: true,
      },
      {
        name: 'selectorType',
        type: 'enum',
        description: 'Type of the selector.',
        enumOptions: ['CSS', 'XPATH'],
        optional: true,
      },
      {
        name: 'delay',
        type: 'time',
        description: 'Wait delay in milliseconds.',
        optional: true,
      },
    ],
  },
  {
    name: 'force200',
    type: 'boolean',
    description: 'Override goto to always return HTTP 200.',
    default: false,
    advanced: true,
  },
  {
    name: 'gotoRetries',
    type: 'number',
    description: 'Maximum number of navigation retries on failure.',
    default: 1,
    advanced: true,
  },
  {
    name: 'firstRequestTimeout',
    type: 'time',
    description: 'Timeout for the initial page request.',
    default: 31000,
    advanced: true,
  },
  {
    name: 'retryGotoUntilLoadedCSSorXpath',
    type: 'boolean',
    description: 'Retry navigation until loadedXpath/loadedSelector is found.',
    default: false,
    advanced: true,
  },
  {
    name: 'useFetch',
    type: 'boolean',
    description: 'Use HTTP fetch instead of browser navigation.',
    default: false,
    advanced: true,
  },
  {
    name: 'browserFetch',
    type: 'boolean',
    description: 'Execute fetch from browser context instead of backend.',
    default: false,
    advanced: true,
  },
  {
    name: 'fromAboutBlank',
    type: 'boolean',
    description: 'Navigate to about:blank first before the target URL.',
    default: true,
    advanced: true,
  },
  {
    name: 'useLambda',
    type: 'enum',
    description: 'Use a Lambda backend for navigation.',
    default: 'None',
    enumOptions: ['None', 'Windmill', 'AWS'],
    advanced: true,
  },
  {
    name: 'captureRequests',
    type: 'boolean',
    description: 'Enable network request capturing during navigation.',
    default: false,
    advanced: true,
  },
  {
    name: 'turnOffTableNormalize',
    type: 'boolean',
    description: 'Disable automatic HTML table normalization.',
    default: false,
    advanced: true,
  },
  {
    name: 'applyIgnoreVBAndCookies',
    type: 'boolean',
    description: 'Ignore virtual browser settings and cookies.',
    default: false,
    advanced: true,
  },
];

export const GOTO2_GROUPS: Record<string, string[]> = {
  'Network': [
    'blockUnnecessaryRequests',
    'setBlockAds',
    'setBypassCSP',
    'setLoadAllResources',
    'setLoadImages',
    'setCssEnabled',
  ],
  'Navigation': [
    'timeout',
    'waitUntil',
    'force200',
    'gotoRetries',
    'firstRequestTimeout',
    'fromAboutBlank',
    'retryGotoUntilLoadedCSSorXpath',
  ],
  'Cookies': [
    'acceptCookiesCSSSelector',
    'waitForCookiesSelectorTimeout',
  ],
  'Captcha': [
    'captchaSelectors',
    'submitCaptchaButtonCSS',
    'maxCaptcha',
    'captchaTimeout',
  ],
  'Advanced': [
    'waitAfterNavObject',
    'useFetch',
    'browserFetch',
    'useLambda',
    'captureRequests',
    'turnOffTableNormalize',
    'applyIgnoreVBAndCookies',
  ],
};
