module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    // blockUnnecessaryRequests: [
    //   '<font|stylesheet>',
    // ],
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    acceptCookiesCSSSelector: null,
    timeout: 60000,
    wait: 9000,
    waitForCookiesSelectorTimeout: 3000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 31000,
    optTags: null,
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: true,
    rawOptions: {},
    captchaSelectors: {
      NAVER: {
        questionElement: '#captcha_info',
        inputElement: 'input#captcha',
        imageElement: '#captchaimg',
      },
    },
    submitCaptchaButtonCSS: null,
    sumbitCaptchaOrderedActions: [
      {
        selectorOrXpath: '//*[contains(@id,"pw")]//input',
        inputValue: '{pswdUsr}',
        wait: 500,
      },
      {
        selectorOrXpath: '//*[@id="log.login"]',
        wait: 9000,
        captchaCheck: true,
      },
    ],
    maxCaptcha: 3,
    captchaTimeout: 100,
    timeoutOffset: 1000,
    waitUntil: 'networkidle0',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    country: 'KR',
    domain: 'naver',
    schemaYAML: 'singlePage',
  },
};
