module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      '<xhr|script|font|stylesheet>',
      'jpeg',
    ],
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: false,
    setCssEnabled: false,
    acceptCookiesCSSSelector: 'button[aria-label="closeDialogLabel"]',
    timeout: 60000,
    waitForCookiesSelectorTimeout: 3000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 31000,
    optTags: null,
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: null,
    rawOptions: {},
    captchaSelectors: { PERIMETERX: 'div#px-captcha' },
    submitCaptchaButtonCSS: null,
    maxCaptcha: 3,
    captchaTimeout: 5000,
    timeoutOffset: 1000,
    waitUntil: 'networkidle0',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    country: 'US',
    domain: 'walmart',
    schemaYAML: 'multiPages',
  },
};
