module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    loadedXpath: null,
    noResultsXPath: '//div[contains(text(), "This page couldn")][contains(text(), "t be found.")] | //div[contains(text(),"We could not find a match")] ',
    accessDeniedXPath: 'dummy',
    loadingTimeout: 5000,
    waitForSelectorToLoad: null,
    URLTemplate: null,
    resultsTarget: 700,
    orderedSelectorsToClickOn: [],
    arrayOfInputFieldNamesToAdd: [],
    zipcode: null,
    maxScrolls: 0,
    setZipCode: {},
    orderedActionsToPerform: [],
    addAttributeToExtractedRecords: null,
    allowScreenCaptures: null,
    checkXpathBeforeExtract: null,
    reloadXpath: null,
    loadedSelector: null,
    preProcessInputs: [],
    useGoto2: true,
    enableAutoTable: true,
    mergeType: 'APPEND',
    schemaYAML: 'multiPages',
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    country: 'US',
    domain: 'walmart',
  },
};
