module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      '<xhr|script|font|stylesheet>',
    ],
    setBlockAds: false,
    setBypassCSP: false,
    setLoadAllResources: false,
    setLoadImages: false,
    setCssEnabled: false,
    acceptCookiesCSSSelector: 'input[name="agree_to_cookies"], p[class="fc-button-label"]',
    timeout: 60000,
    waitForCookiesSelectorTimeout: 3000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 60000,
    optTags: null,
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: null,
    rawOptions: {},
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    maxCaptcha: 3,
    captchaTimeout: 5000,
    timeoutOffset: 1000,
    waitUntil: 'networkidle0',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    country: 'UK',
    domain: 'home-co',
    schemaYAML: 'multiPages',
  },
};
