// ISO 3166-1 alpha-2 country codes
export const COUNTRIES: { code: string; name: string }[] = [
  { code: "AD", name: "Andorra" }, { code: "AE", name: "United Arab Emirates" }, { code: "AF", name: "Afghanistan" },
  { code: "AG", name: "Antigua and Barbuda" }, { code: "AI", name: "Anguilla" }, { code: "AL", name: "Albania" },
  { code: "AM", name: "Armenia" }, { code: "AO", name: "Angola" }, { code: "AQ", name: "Antarctica" },
  { code: "AR", name: "Argentina" }, { code: "AS", name: "American Samoa" }, { code: "AT", name: "Austria" },
  { code: "AU", name: "Australia" }, { code: "AW", name: "Aruba" }, { code: "AX", name: "Åland Islands" },
  { code: "AZ", name: "Azerbaijan" }, { code: "BA", name: "Bosnia and Herzegovina" }, { code: "BB", name: "Barbados" },
  { code: "BD", name: "Bangladesh" }, { code: "BE", name: "Belgium" }, { code: "BF", name: "Burkina Faso" },
  { code: "BG", name: "Bulgaria" }, { code: "BH", name: "Bahrain" }, { code: "BI", name: "Burundi" },
  { code: "BJ", name: "Benin" }, { code: "BL", name: "Saint Barthélemy" }, { code: "BM", name: "Bermuda" },
  { code: "BN", name: "Brunei" }, { code: "BO", name: "Bolivia" }, { code: "BQ", name: "Caribbean Netherlands" },
  { code: "BR", name: "Brazil" }, { code: "BS", name: "Bahamas" }, { code: "BT", name: "Bhutan" },
  { code: "BW", name: "Botswana" }, { code: "BY", name: "Belarus" }, { code: "BZ", name: "Belize" },
  { code: "CA", name: "Canada" }, { code: "CC", name: "Cocos Islands" }, { code: "CD", name: "DR Congo" },
  { code: "CF", name: "Central African Republic" }, { code: "CG", name: "Congo" }, { code: "CH", name: "Switzerland" },
  { code: "CI", name: "Côte d'Ivoire" }, { code: "CK", name: "Cook Islands" }, { code: "CL", name: "Chile" },
  { code: "CM", name: "Cameroon" }, { code: "CN", name: "China" }, { code: "CO", name: "Colombia" },
  { code: "CR", name: "Costa Rica" }, { code: "CU", name: "Cuba" }, { code: "CV", name: "Cape Verde" },
  { code: "CW", name: "Curaçao" }, { code: "CX", name: "Christmas Island" }, { code: "CY", name: "Cyprus" },
  { code: "CZ", name: "Czechia" }, { code: "DE", name: "Germany" }, { code: "DJ", name: "Djibouti" },
  { code: "DK", name: "Denmark" }, { code: "DM", name: "Dominica" }, { code: "DO", name: "Dominican Republic" },
  { code: "DZ", name: "Algeria" }, { code: "EC", name: "Ecuador" }, { code: "EE", name: "Estonia" },
  { code: "EG", name: "Egypt" }, { code: "EH", name: "Western Sahara" }, { code: "ER", name: "Eritrea" },
  { code: "ES", name: "Spain" }, { code: "ET", name: "Ethiopia" }, { code: "FI", name: "Finland" },
  { code: "FJ", name: "Fiji" }, { code: "FK", name: "Falkland Islands" }, { code: "FM", name: "Micronesia" },
  { code: "FO", name: "Faroe Islands" }, { code: "FR", name: "France" }, { code: "GA", name: "Gabon" },
  { code: "GB", name: "United Kingdom" }, { code: "GD", name: "Grenada" }, { code: "GE", name: "Georgia" },
  { code: "GF", name: "French Guiana" }, { code: "GG", name: "Guernsey" }, { code: "GH", name: "Ghana" },
  { code: "GI", name: "Gibraltar" }, { code: "GL", name: "Greenland" }, { code: "GM", name: "Gambia" },
  { code: "GN", name: "Guinea" }, { code: "GP", name: "Guadeloupe" }, { code: "GQ", name: "Equatorial Guinea" },
  { code: "GR", name: "Greece" }, { code: "GT", name: "Guatemala" }, { code: "GU", name: "Guam" },
  { code: "GW", name: "Guinea-Bissau" }, { code: "GY", name: "Guyana" }, { code: "HK", name: "Hong Kong" },
  { code: "HN", name: "Honduras" }, { code: "HR", name: "Croatia" }, { code: "HT", name: "Haiti" },
  { code: "HU", name: "Hungary" }, { code: "ID", name: "Indonesia" }, { code: "IE", name: "Ireland" },
  { code: "IL", name: "Israel" }, { code: "IM", name: "Isle of Man" }, { code: "IN", name: "India" },
  { code: "IO", name: "British Indian Ocean Territory" }, { code: "IQ", name: "Iraq" }, { code: "IR", name: "Iran" },
  { code: "IS", name: "Iceland" }, { code: "IT", name: "Italy" }, { code: "JE", name: "Jersey" },
  { code: "JM", name: "Jamaica" }, { code: "JO", name: "Jordan" }, { code: "JP", name: "Japan" },
  { code: "KE", name: "Kenya" }, { code: "KG", name: "Kyrgyzstan" }, { code: "KH", name: "Cambodia" },
  { code: "KI", name: "Kiribati" }, { code: "KM", name: "Comoros" }, { code: "KN", name: "Saint Kitts and Nevis" },
  { code: "KP", name: "North Korea" }, { code: "KR", name: "South Korea" }, { code: "KW", name: "Kuwait" },
  { code: "KY", name: "Cayman Islands" }, { code: "KZ", name: "Kazakhstan" }, { code: "LA", name: "Laos" },
  { code: "LB", name: "Lebanon" }, { code: "LC", name: "Saint Lucia" }, { code: "LI", name: "Liechtenstein" },
  { code: "LK", name: "Sri Lanka" }, { code: "LR", name: "Liberia" }, { code: "LS", name: "Lesotho" },
  { code: "LT", name: "Lithuania" }, { code: "LU", name: "Luxembourg" }, { code: "LV", name: "Latvia" },
  { code: "LY", name: "Libya" }, { code: "MA", name: "Morocco" }, { code: "MC", name: "Monaco" },
  { code: "MD", name: "Moldova" }, { code: "ME", name: "Montenegro" }, { code: "MF", name: "Saint Martin" },
  { code: "MG", name: "Madagascar" }, { code: "MH", name: "Marshall Islands" }, { code: "MK", name: "North Macedonia" },
  { code: "ML", name: "Mali" }, { code: "MM", name: "Myanmar" }, { code: "MN", name: "Mongolia" },
  { code: "MO", name: "Macau" }, { code: "MP", name: "Northern Mariana Islands" }, { code: "MQ", name: "Martinique" },
  { code: "MR", name: "Mauritania" }, { code: "MS", name: "Montserrat" }, { code: "MT", name: "Malta" },
  { code: "MU", name: "Mauritius" }, { code: "MV", name: "Maldives" }, { code: "MW", name: "Malawi" },
  { code: "MX", name: "Mexico" }, { code: "MY", name: "Malaysia" }, { code: "MZ", name: "Mozambique" },
  { code: "NA", name: "Namibia" }, { code: "NC", name: "New Caledonia" }, { code: "NE", name: "Niger" },
  { code: "NF", name: "Norfolk Island" }, { code: "NG", name: "Nigeria" }, { code: "NI", name: "Nicaragua" },
  { code: "NL", name: "Netherlands" }, { code: "NO", name: "Norway" }, { code: "NP", name: "Nepal" },
  { code: "NR", name: "Nauru" }, { code: "NU", name: "Niue" }, { code: "NZ", name: "New Zealand" },
  { code: "OM", name: "Oman" }, { code: "PA", name: "Panama" }, { code: "PE", name: "Peru" },
  { code: "PF", name: "French Polynesia" }, { code: "PG", name: "Papua New Guinea" }, { code: "PH", name: "Philippines" },
  { code: "PK", name: "Pakistan" }, { code: "PL", name: "Poland" }, { code: "PM", name: "Saint Pierre and Miquelon" },
  { code: "PN", name: "Pitcairn Islands" }, { code: "PR", name: "Puerto Rico" }, { code: "PS", name: "Palestine" },
  { code: "PT", name: "Portugal" }, { code: "PW", name: "Palau" }, { code: "PY", name: "Paraguay" },
  { code: "QA", name: "Qatar" }, { code: "RE", name: "Réunion" }, { code: "RO", name: "Romania" },
  { code: "RS", name: "Serbia" }, { code: "RU", name: "Russia" }, { code: "RW", name: "Rwanda" },
  { code: "SA", name: "Saudi Arabia" }, { code: "SB", name: "Solomon Islands" }, { code: "SC", name: "Seychelles" },
  { code: "SD", name: "Sudan" }, { code: "SE", name: "Sweden" }, { code: "SG", name: "Singapore" },
  { code: "SH", name: "Saint Helena" }, { code: "SI", name: "Slovenia" }, { code: "SJ", name: "Svalbard" },
  { code: "SK", name: "Slovakia" }, { code: "SL", name: "Sierra Leone" }, { code: "SM", name: "San Marino" },
  { code: "SN", name: "Senegal" }, { code: "SO", name: "Somalia" }, { code: "SR", name: "Suriname" },
  { code: "SS", name: "South Sudan" }, { code: "ST", name: "São Tomé and Príncipe" }, { code: "SV", name: "El Salvador" },
  { code: "SX", name: "Sint Maarten" }, { code: "SY", name: "Syria" }, { code: "SZ", name: "Eswatini" },
  { code: "TC", name: "Turks and Caicos" }, { code: "TD", name: "Chad" }, { code: "TF", name: "French Southern Territories" },
  { code: "TG", name: "Togo" }, { code: "TH", name: "Thailand" }, { code: "TJ", name: "Tajikistan" },
  { code: "TK", name: "Tokelau" }, { code: "TL", name: "Timor-Leste" }, { code: "TM", name: "Turkmenistan" },
  { code: "TN", name: "Tunisia" }, { code: "TO", name: "Tonga" }, { code: "TR", name: "Turkey" },
  { code: "TT", name: "Trinidad and Tobago" }, { code: "TV", name: "Tuvalu" }, { code: "TW", name: "Taiwan" },
  { code: "TZ", name: "Tanzania" }, { code: "UA", name: "Ukraine" }, { code: "UG", name: "Uganda" },
  { code: "US", name: "United States" }, { code: "UY", name: "Uruguay" }, { code: "UZ", name: "Uzbekistan" },
  { code: "VA", name: "Vatican City" }, { code: "VC", name: "Saint Vincent" }, { code: "VE", name: "Venezuela" },
  { code: "VG", name: "British Virgin Islands" }, { code: "VI", name: "US Virgin Islands" }, { code: "VN", name: "Vietnam" },
  { code: "VU", name: "Vanuatu" }, { code: "WF", name: "Wallis and Futuna" }, { code: "WS", name: "Samoa" },
  { code: "XK", name: "Kosovo" }, { code: "YE", name: "Yemen" }, { code: "YT", name: "Mayotte" },
  { code: "ZA", name: "South Africa" }, { code: "ZM", name: "Zambia" }, { code: "ZW", name: "Zimbabwe" },
];

// ISO 639-1 language codes (common subset)
export const LANGUAGES: { code: string; name: string }[] = [
  { code: "aa", name: "Afar" }, { code: "ab", name: "Abkhazian" }, { code: "af", name: "Afrikaans" },
  { code: "am", name: "Amharic" }, { code: "ar", name: "Arabic" }, { code: "as", name: "Assamese" },
  { code: "az", name: "Azerbaijani" }, { code: "be", name: "Belarusian" }, { code: "bg", name: "Bulgarian" },
  { code: "bn", name: "Bengali" }, { code: "bo", name: "Tibetan" }, { code: "bs", name: "Bosnian" },
  { code: "ca", name: "Catalan" }, { code: "cs", name: "Czech" }, { code: "cy", name: "Welsh" },
  { code: "da", name: "Danish" }, { code: "de", name: "German" }, { code: "el", name: "Greek" },
  { code: "en", name: "English" }, { code: "es", name: "Spanish" }, { code: "et", name: "Estonian" },
  { code: "eu", name: "Basque" }, { code: "fa", name: "Persian" }, { code: "fi", name: "Finnish" },
  { code: "fil", name: "Filipino" }, { code: "fr", name: "French" }, { code: "ga", name: "Irish" },
  { code: "gl", name: "Galician" }, { code: "gu", name: "Gujarati" }, { code: "he", name: "Hebrew" },
  { code: "hi", name: "Hindi" }, { code: "hr", name: "Croatian" }, { code: "hu", name: "Hungarian" },
  { code: "hy", name: "Armenian" }, { code: "id", name: "Indonesian" }, { code: "is", name: "Icelandic" },
  { code: "it", name: "Italian" }, { code: "ja", name: "Japanese" }, { code: "ka", name: "Georgian" },
  { code: "kk", name: "Kazakh" }, { code: "km", name: "Khmer" }, { code: "kn", name: "Kannada" },
  { code: "ko", name: "Korean" }, { code: "ku", name: "Kurdish" }, { code: "ky", name: "Kyrgyz" },
  { code: "lo", name: "Lao" }, { code: "lt", name: "Lithuanian" }, { code: "lv", name: "Latvian" },
  { code: "mk", name: "Macedonian" }, { code: "ml", name: "Malayalam" }, { code: "mn", name: "Mongolian" },
  { code: "mr", name: "Marathi" }, { code: "ms", name: "Malay" }, { code: "mt", name: "Maltese" },
  { code: "my", name: "Burmese" }, { code: "ne", name: "Nepali" }, { code: "nl", name: "Dutch" },
  { code: "no", name: "Norwegian" }, { code: "pa", name: "Punjabi" }, { code: "pl", name: "Polish" },
  { code: "ps", name: "Pashto" }, { code: "pt", name: "Portuguese" }, { code: "ro", name: "Romanian" },
  { code: "ru", name: "Russian" }, { code: "rw", name: "Kinyarwanda" }, { code: "si", name: "Sinhala" },
  { code: "sk", name: "Slovak" }, { code: "sl", name: "Slovenian" }, { code: "so", name: "Somali" },
  { code: "sq", name: "Albanian" }, { code: "sr", name: "Serbian" }, { code: "sv", name: "Swedish" },
  { code: "sw", name: "Swahili" }, { code: "ta", name: "Tamil" }, { code: "te", name: "Telugu" },
  { code: "th", name: "Thai" }, { code: "tl", name: "Tagalog" }, { code: "tr", name: "Turkish" },
  { code: "uk", name: "Ukrainian" }, { code: "ur", name: "Urdu" }, { code: "uz", name: "Uzbek" },
  { code: "vi", name: "Vietnamese" }, { code: "zh", name: "Chinese" }, { code: "zu", name: "Zulu" },
];

// ISO 4217 currency codes (common subset)
export const CURRENCIES: { code: string; name: string }[] = [
  { code: "AED", name: "UAE Dirham" }, { code: "ARS", name: "Argentine Peso" }, { code: "AUD", name: "Australian Dollar" },
  { code: "BDT", name: "Bangladeshi Taka" }, { code: "BGN", name: "Bulgarian Lev" }, { code: "BHD", name: "Bahraini Dinar" },
  { code: "BRL", name: "Brazilian Real" }, { code: "CAD", name: "Canadian Dollar" }, { code: "CHF", name: "Swiss Franc" },
  { code: "CLP", name: "Chilean Peso" }, { code: "CNY", name: "Chinese Yuan" }, { code: "COP", name: "Colombian Peso" },
  { code: "CZK", name: "Czech Koruna" }, { code: "DKK", name: "Danish Krone" }, { code: "EGP", name: "Egyptian Pound" },
  { code: "EUR", name: "Euro" }, { code: "GBP", name: "Pound Sterling" }, { code: "GHS", name: "Ghanaian Cedi" },
  { code: "HKD", name: "Hong Kong Dollar" }, { code: "HUF", name: "Hungarian Forint" }, { code: "IDR", name: "Indonesian Rupiah" },
  { code: "ILS", name: "Israeli Shekel" }, { code: "INR", name: "Indian Rupee" }, { code: "IQD", name: "Iraqi Dinar" },
  { code: "ISK", name: "Icelandic Króna" }, { code: "JPY", name: "Japanese Yen" }, { code: "KES", name: "Kenyan Shilling" },
  { code: "KRW", name: "South Korean Won" }, { code: "KWD", name: "Kuwaiti Dinar" }, { code: "MAD", name: "Moroccan Dirham" },
  { code: "MXN", name: "Mexican Peso" }, { code: "MYR", name: "Malaysian Ringgit" }, { code: "NGN", name: "Nigerian Naira" },
  { code: "NOK", name: "Norwegian Krone" }, { code: "NZD", name: "New Zealand Dollar" }, { code: "PEN", name: "Peruvian Sol" },
  { code: "PHP", name: "Philippine Peso" }, { code: "PKR", name: "Pakistani Rupee" }, { code: "PLN", name: "Polish Zloty" },
  { code: "QAR", name: "Qatari Riyal" }, { code: "RON", name: "Romanian Leu" }, { code: "RUB", name: "Russian Ruble" },
  { code: "SAR", name: "Saudi Riyal" }, { code: "SEK", name: "Swedish Krona" }, { code: "SGD", name: "Singapore Dollar" },
  { code: "THB", name: "Thai Baht" }, { code: "TRY", name: "Turkish Lira" }, { code: "TWD", name: "Taiwan Dollar" },
  { code: "UAH", name: "Ukrainian Hryvnia" }, { code: "USD", name: "US Dollar" }, { code: "UYU", name: "Uruguayan Peso" },
  { code: "VND", name: "Vietnamese Dong" }, { code: "ZAR", name: "South African Rand" },
];

// Data centers
export const DATA_CENTERS: string[] = [
  "AUS", "BRA", "CAN", "CUS", "DEU", "ESP", "FRA", "GBR", "GLB",
  "IIO", "IJK", "IND", "ITA", "JPN", "KOR", "PUS", "USA", "USX", "WWW", "ZAF",
];

// Proxy types
export const PROXY_TYPES: string[] = [
  "Data Center", "Residential", "Mixed", "ISP",
];

// Login pool options
export const LOGIN_POOLS: string[] = [
  "No Login Pool",
];

// Domain options (for source creation)
export const DOMAIN_OPTIONS: string[] = [
  "balancer", "nightmare",
];
