module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      '<font|stylesheet>',
    ],
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: false,
    setLoadImages: false,
    setCssEnabled: true,
    acceptCookiesCSSSelector: 'button[aria-label="close"]',
    timeout: 60000,
    waitForCookiesSelectorTimeout: 3000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 31000,
    optTags: '"cookie_jar":[{"name":"preferedstore","value":"2601"}, {"name":"preferredStoreId","value":"2601"}, {"name":"preferredZipCode","value":"46224"}]',
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: null,
    rawOptions: {},
    captchaSelectors: { PERIMETERX: '#px-captcha' },
    submitCaptchaButtonCSS: null,
    maxCaptcha: 3,
    captchaTimeout: 5000,
    timeoutOffset: 1000,
    waitUntil: 'networkidle0',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    country: 'US',
    domain: 'autozone',
    schemaYAML: 'singlePage',
  },
};
