module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'CZ',
    loadedXpath: '//h1',
    waitForSelectorToLoad: null,
    noResultsXPath: '//h1[contains(text(),"404")] | //*[contains(@class,"h2 text-center hidden-xs") and contains(text(), "INTERNAL SERVER")]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    orderedSelectorsToClickOn: [],
    loadingTimeout: 5000,
    URLTemplate: null,
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'singlePage',
    mergeType: 'APPEND',
    maxScrolls: 0,
    arrayOfInputFieldNamesToAdd: null,
    enableAutoTable: true,
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    domain: 'ticketportal',
  },
};
