module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'BE',
    loadedSelector: null,
    waitForSelectorToLoad: null,
    noResultsXPath: '//h1[contains(text(),"404")] | //div[@id="aod-container"]//div[@id="aod-pinned-offer"][not(contains(., "Aucune offre mise en avant"))]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    orderedSelectorsToClickOn: [
      '.redir-dismiss-x',
      '#sp-cc-accept',
    ],
    orderedActionsToPerform: [],
    loadingTimeout: 5000,
    checkXpathBeforeExtract: null,
    URLTemplate: null,
    setZipCode: {
      checkZipCodeSelectorOrXPath: null,
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'singlePage',
    mergeType: 'APPEND',
    maxScrolls: 3,
    arrayOfInputFieldNamesToAdd: null,
    addAttributeToExtractedRecords: null,
    enableAutoTable: true,
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    domain: 'amazon',
  },
};
