module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'DE',
    loadedSelector: null,
    waitForSelectorToLoad: '.SearchResultListProducts__Item',
    noResultsXPath: '//h1[contains(text(),"404")]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    loadingTimeout: 10000,
    URLTemplate: null,
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'multiPages',
    mergeType: 'APPEND',
    maxScrolls: 3,
    arrayOfInputFieldNamesToAdd: null,
    enableAutoTable: true,
    domain: 'porta',
  },
};
