module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      // '<xhr|script|font|stylesheet>',
    ],
    setBlockAds: true,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: null,
    setCssEnabled: null,
    acceptCookiesCSSSelector: '#onetrust-accept-btn-handler',
    timeout: 60000,
    waitForCookiesSelectorTimeout: 3000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 31000,
    optTags: null,
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: null,
    useFetch: null,
    browserFetch: null,
    rawOptions: {},
    captchaSelectors: {},
    sumbitCaptchaOrderedActions: [],
    submitCaptchaButtonCSS: null,
    maxCaptcha: 3,
    captchaTimeout: 5000,
    timeoutOffset: 1000,
    waitUntil: 'load',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    domain: 'bunzlchs',
    country: 'UK',
    schemaYAML: 'extractor',
  },
};
