module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    loadedXpath: '//div[contains(@class, "product__listing") and contains(@class, "product__grid")] | //*[contains(@class,"product-main-info")]',
    noResultsXPath: '//div[contains(@class, "global-alerts")]/*',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    loadingTimeout: 10000,
    waitForSelectorToLoad: null,
    URLTemplate: '{url}?pages=20',
    resultsTarget: 1,
    orderedSelectorsToClickOn: [],
    arrayOfInputFieldNamesToAdd: [],
    zipcode: null,
    maxScrolls: 10,
    setZipCode: {
      checkZipCodeSelectorOrXPath: '',
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    orderedActionsToPerform: [],
    addAttributeToExtractedRecords: null,
    allowScreenCaptures: null,
    checkXpathBeforeExtract: null,
    reloadXpath: null,
    loadedSelector: null,
    appendCookies: 'false',
    preProcessInputs: [],
    useGoto2: true,
    enableAutoTable: true,
    mergeType: 'APPEND',
    schemaYAML: 'extractor',
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    country: 'UK',
    domain: 'bunzlchs',
  },
};
