module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'GB',
    loadedXpath: '//main',
    waitForSelectorToLoad: null,
    noResultsXPath: '//h1[contains(text(),"404")]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    orderedSelectorsToClickOn: [],
    loadingTimeout: 5000,
    URLTemplate: null,
    zipcode: 'NW10 0TH',
    storeID: null,
    useGoto2: true,
    schemaYAML: 'multiPages',
    mergeType: 'APPEND',
    maxScrolls: 3,
    arrayOfInputFieldNamesToAdd: null,
    enableAutoTable: true,
    // paginate: {
    //   stopConditionSelectorOrXpath: null,
    //   nestedPagination: {
    //     nextDepthURLFieldName: null,
    //     paginate: null,
    //   },
    //   nextLink: {
    //     nextLinkSelectorOrXpath: null,
    //     mutationSelectorOrXpath: null,
    //     spinnerSelectorOrXpath: null,
    //     nextLinkTimeout: null,
    //     waitForXpath: null,
    //   },
    //   infiniteScroll: {
    //     maxScrolls: null,
    //     stopXPath: null,
    //     waitTime: null,
    //   },
    //   openSearchDefinition: {
    //     template: null,
    //     pageStartNb: null,
    //     indexOffset: null,
    //     pageOffset: null,
    //     pageIndexMultiplier: null,
    //   },
    // },
    domain: 'ikea',
  },
};
