module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      // '<font|stylesheet>',
    ],
    setBlockAds: false,
    setBypassCSP: false,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 60000,
    waitUntil: 'networkidle0',
    rawOptions: null,
    acceptCookiesCSSSelector: null,
    captchaSelectors: { IMAGECAPTCHA: { inputElement: '#ans', imageElement: 'img[alt="Red dot"]' } },
    maxCaptcha: 4,
    submitCaptchaButtonCSS: '#jar',
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    retryGotoUntilLoadedCSSorXpath: null,
    store: null,
    country: 'US',
    gotoRetries: null,
    domain: 'tjx',
    schemaYAML: 'singlePage',
  },
};
