module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: null,
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: false,
    setCssEnabled: false,
    acceptCookiesCSSSelector: '[id="onetrust-accept-btn-handler"]',
    timeout: 60000,
    waitForCookiesSelectorTimeout: 5000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 35000,
    optTags: null,
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: null,
    rawOptions: {},
    // captchaSelectors: { GEETEST: 'iframe[src*="geo.captcha"]' },
    submitCaptchaButtonCSS: null,
    maxCaptcha: 3,
    captchaTimeout: 5000,
    timeoutOffset: 1000,
    waitUntil: 'networkidle0',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    country: 'US',
    domain: 'mouser',
    schemaYAML: 'multiPages',
  },
};
