module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    loadedXpath: null,
    noResultsXPath: '//h1[contains(text(),"404")]',
    accessDeniedXPath: '//*[@id="cmsg"][text()="Please enable JS and disable any ad blocker"] | //h1[contains(text(),"Access Denied")]',
    loadingTimeout: 10000,
    waitForSelectorToLoad: null,
    URLTemplate: null,
    resultsTarget: 1,
    orderedSelectorsToClickOn: [],
    arrayOfInputFieldNamesToAdd: [],
    zipcode: null,
    maxScrolls: 0,
    setZipCode: {
      checkZipCodeSelectorOrXPath: '',
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    orderedActionsToPerform: [],
    addAttributeToExtractedRecords: null,
    allowScreenCaptures: null,
    checkXpathBeforeExtract: null,
    reloadXpath: null,
    loadedSelector: null,
    preProcessInputs: [],
    useGoto2: true,
    enableAutoTable: true,
    mergeType: 'APPEND',
    schemaYAML: 'multiPages',
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    country: 'US',
    domain: 'mouser',
  },
};
