module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'JP',
    loadedSelector: 'main',
    waitForSelectorToLoad: null,
    noResultsXPath: '//strong[contains(text(), "ご指定のページが見つかりません")] | //section[@class="performance-list-panel"]//span[contains(@class, "label-price-txt")]//*[contains(text(), "0,0")] | //div[contains(@class, "regular-section")]//p[contains(@class, "info-line")][contains(text(), "0,0")]',
    accessDeniedXPath: '//h2[contains(text(), "アクセスが集中してお")] | //title[contains(text(), \'ご確認ください\')]',
    orderedSelectorsToClickOn: [],
    orderedActionsToPerform: [],
    loadingTimeout: 5000,
    checkXpathBeforeExtract: null,
    URLTemplate: null,
    setZipCode: {
      checkZipCodeSelectorOrXPath: null,
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'multipages',
    mergeType: 'APPEND',
    maxScrolls: 0,
    arrayOfInputFieldNamesToAdd: null,
    addAttributeToExtractedRecords: null,
    enableAutoTable: false,
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    domain: 'johnnys',
  },
};
