module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: [
      'jpeg', 'jpg', '<font|stylesheet>',
    ],
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: false,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 120000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: 'div#consent_prompt_submit',
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'UK',
    gotoRetries: null,
    rawOptions: { checkBlocked: true },
    domain: 'nisbets',
    schemaYAML: 'extractor',
  },
};
