module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: 1000,
    country: 'UK',
    loadedXpath: '//ul[contains(@class, "brand-index__list")]/li | //div[@id="product-results-list"]//*[contains(@class,"product-list-grid-item") and (contains(@class, "default-item") or contains(@class, "parent-item"))]|//div[contains(@class, "product-listing__pagination")][contains(@class, "empty-result")]',
    noResultsXPath: '//div[contains(@class, "error_page")]',
    waitForSelectorToLoad: null,
    accessDeniedXPath: '//div[@id="cf-error-details"]',
    orderedSelectorsToClickOn: [],
    orderedActionsToPerform: [],
    loadingTimeout: 60000,
    checkXpathBeforeExtract: null,
    URLTemplate: null,
    setZipCode: {
      checkZipCodeSelectorOrXPath: null,
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'extractor',
    mergeType: 'APPEND',
    maxScrolls: 0,
    arrayOfInputFieldNamesToAdd: null,
    addAttributeToExtractedRecords: null,
    enableAutoTable: true,
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    domain: 'nisbets',
  },
};
