module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'DE',
    loadedSelector: '#main',
    waitForSelectorToLoad: 'div.cm_secondary_button',
    noResultsXPath: '//h1[@data-purpose="error404.heading"]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    // orderedSelectorsToClickOn: ['button[data-purpose="informationSection.modal.button"]:first-of-type'],
    orderedActionsToPerform: [
      { selectorOrXpath: '.cm_content button[title]', inputValue: '', wait: 10000 },
      { selectorOrXpath: "(//div[@data-purpose='modal.default.wrapper']//button)[1]", inputValue: '', wait: 2000 },
      { selectorOrXpath: "//*[contains(@data-purpose,'informationSection.modal.button')][1]", inputValue: '', wait: 2000 },
    ],
    loadingTimeout: 120000,
    URLTemplate: null,
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'multiPages',
    mergeType: 'APPEND',
    maxScrolls: 3,
    arrayOfInputFieldNamesToAdd: null,
    enableAutoTable: true,
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    domain: 'xxlutz',
  },
};
