module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'SE',
    loadedSelector: 'main',
    waitForSelectorToLoad: null,
    noResultsXPath: "//h1[contains(text(), 'Sidan kunde inte hittas')]",
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    orderedSelectorsToClickOn: [],
    loadingTimeout: 10000,
    URLTemplate: null,
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'multiPages',
    mergeType: 'APPEND',
    maxScrolls: 3,
    arrayOfInputFieldNamesToAdd: null,
    enableAutoTable: true,
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    domain: 'ahlens',
  },
};
