module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: null,
    setBlockAds: false,
    setBypassCSP: false,
    setLoadAllResources: false,
    setLoadImages: false,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 60000,
    waitUntil: 'networkidle0',
    rawOptions: {},
    acceptCookiesCSSSelector: null,
    captchaSelectors: {},
    submitCaptchaButtonCSS: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    retryGotoUntilLoadedCSSorXpath: null,
    store: null,
    country: 'US',
    gotoRetries: null,
    domain: 'jcp1seg',
    schemaYAML: 'singlePage',
  },
};
