module.exports = {
  implements: 'robots/san-antonio',
  parameterValues: {
    resultsTarget: null,
    country: 'HU',
    loadedXPath: null,
    waitForSelectorToLoad: null,
    noResultsXPath: '//h1[contains(text(),"404")] | //*[contains(@data-purpose,"error404")]',
    accessDeniedXPath: '//h1[contains(text(),"Denied")]',
    orderedSelectorsToClickOn: [],
    orderedActionsToPerform: [
      { selectorOrXpath: '.cm_content button[title]', inputValue: '', wait: 2000 },
      { selectorOrXpath: "(//div[@data-purpose='modal.default.wrapper']//button)[1]", inputValue: '', wait: 2000 },
      { selectorOrXpath: "//*[contains(@data-purpose,'informationSection.modal.button')][1]", inputValue: '', wait: 2000 },
    ],
    loadingTimeout: 10000,
    URLTemplate: null,
    setZipCode: {
      checkZipCodeSelectorOrXPath: null,
      maxTries: 1,
      setZipWithUI: {
        beforeInputSelectorOrXpathArray: null,
        inputSelectorOrXPath: null,
        afterInputSelectorOrXPathArray: null,
        wait: 3000,
      },
    },
    zipcode: null,
    storeID: null,
    useGoto2: true,
    schemaYAML: 'multiPages',
    mergeType: 'APPEND',
    maxScrolls: 3,
    arrayOfInputFieldNamesToAdd: null,
    addAttributeToExtractedRecords: null,
    enableAutoTable: true,
    paginate: {
      stopConditionSelectorOrXpath: null,
      nestedPagination: {
        nextDepthURLFieldName: null,
        paginate: null,
      },
      nextLink: {
        nextLinkSelectorOrXpath: null,
        mutationSelectorOrXpath: null,
        spinnerSelectorOrXpath: null,
        nextLinkTimeout: null,
        waitForXpath: null,
      },
      infiniteScroll: {
        maxScrolls: null,
        stopXPath: null,
        waitTime: null,
      },
      openSearchDefinition: {
        template: null,
        pageStartNb: null,
        indexOffset: null,
        pageOffset: null,
        pageIndexMultiplier: null,
      },
    },
    domain: 'xxxl',
  },
};
