module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: null,
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: null,
    setCssEnabled: null,
    acceptCookiesCSSSelector: '[class*="allow"], [id*="accept-btn"], [aria-label="Accept All"]',
    timeout: 60000,
    waitForCookiesSelectorTimeout: 10000,
    force200: null,
    gotoRetries: 1,
    firstRequestTimeout: 31000,
    optTags: null,
    retryGotoUntilLoadedCSSorXpath: null,
    captureRequests: null,
    rawOptions: {},
    captchaSelectors: {}, // PERIMETERX: 'div[id="px-captcha"]'
    submitCaptchaButtonCSS: null,
    maxCaptcha: 3,
    captchaTimeout: 5000,
    timeoutOffset: 1000,
    waitUntil: 'networkidle0',
    applyIgnoreVBAndCookies: null,
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: 0,
    },
    country: 'US',
    domain: 'potoo_screenshot',
    schemaYAML: 'singlePage',
  },
};
