module.exports = {
  implements: 'navigation/goto2',
  parameterValues: {
    blockUnnecessaryRequests: false,
    setBlockAds: false,
    setBypassCSP: true,
    setLoadAllResources: true,
    setLoadImages: true,
    setCssEnabled: true,
    applyIgnoreVBAndCookies: null,
    optTags: null,
    timeout: 60000,
    firstRequestTimeout: 51000,
    waitUntil: 'networkidle0',
    acceptCookiesCSSSelector: '.accept-cookies-button',
    captchaSelectors: { IMAGECAPTCHA: { inputElement: '#solution', imageElement: 'img.captcha-code' } },
    submitCaptchaButtonCSS: '.botdetect-button.btn',
    waitAfterNavObject: {
      wrongRedirectSelector: '',
      selector: '',
      selectorType: '',
      delay: null,
    },
    store: null,
    country: 'UK',
    domain: 'ticketfactory',
    schemaYAML: 'multiPages',
  },
};
